Find the point group of a lattice.

In [39]:
import numpy as np
from numpy.linalg import norm
from BZI.symmetry import Lattice
from BZI.sampling import sphere_pts

In [69]:
# Build lattice
center_type = "prim"
lat_consts = [1]*3
lat_angles = [np.pi/2]*3
lattice = Lattice(center_type, lat_consts, lat_angles)

In [70]:
# Build a grid within a sphere for this lattice.
pts = sphere_pts(lattice.vectors, 3)

In [72]:
# Build the operators.
point_group = []
for p1 in pts:
    p1 = np.array(p1)
    for p2 in pts:
        p2 = np.array(p2)
        if np.isclose(np.dot(p1,p1), np.dot(p2,p2)):
            if np.allclose(p1,p2):
                continue
            else:
                ip2 = p2/(np.dot(p2,p2))
                op = np.outer(ip2,p1)
                print(np.linalg.det(op))
                try:
                    det = np.linalg.det(op)
                    if np.isclose(abs(det),1):
                        point_group.append(op)
                except:
                    continue

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
-2.01726527317e-67
0.0
0.0
0.0
0.0
0.0
0.0
2.01726527317e-67
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.1881365962e-66
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.1881365962e-66
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.01726527317e-67
0.0
0.0
0.0
0.0
0.0
0.0
-2.01726527317e-67
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [49]:
point_group

[]

In [16]:
import numpy as np
from BZI.symmetry import make_ptvecs, make_rptvecs
from BZI.sampling import make_cell_points
from BZI.pseudopots import Al_lat_const
from BZI.symmetry import find_orbitals

In [7]:
center_type = "face"
lat_angles = [np.pi/2]*3
lat_consts = [Al_lat_const]*3
lat_vecs = make_ptvecs(center_type, lat_consts, lat_angles)
rlat_vecs = make_rptvecs(lat_vecs)

In [13]:
grid_center_type = "face"
grid_angles = [np.pi/2]*3
grid_constants = [Al_lat_const*5]*3
grid_vecs = make_ptvecs(grid_center_type, grid_constants, grid_angles)
rgrid_vecs = make_rptvecs(grid_vecs)

In [14]:
offset = [0.]*3
grid_pts = make_cell_points(rlat_vecs, rgrid_vecs, offset)

In [24]:
rgrid_vecs

array([[-0.16419352,  0.16419352,  0.16419352],
       [ 0.16419352, -0.16419352,  0.16419352],
       [ 0.16419352,  0.16419352, -0.16419352]])

In [25]:
rlat_vecs

array([[-0.82096758,  0.82096758,  0.82096758],
       [ 0.82096758, -0.82096758,  0.82096758],
       [ 0.82096758,  0.82096758, -0.82096758]])

In [23]:
grid_pts

[array([ 0.,  0.,  0.]),
 array([ 0.16419352,  0.16419352, -0.16419352]),
 array([ 0.32838703,  0.32838703, -0.32838703]),
 array([ 0.49258055,  0.49258055, -0.49258055]),
 array([ 0.65677407,  0.65677407, -0.65677407]),
 array([ 0.16419352, -0.16419352,  0.16419352]),
 array([  3.28387034e-01,   3.04165814e-13,  -3.04210223e-13]),
 array([ 0.49258055,  0.16419352, -0.16419352]),
 array([ 0.65677407,  0.32838703, -0.32838703]),
 array([ 0.82096758,  0.49258055, -0.49258055]),
 array([ 0.32838703, -0.32838703,  0.32838703]),
 array([ 0.49258055, -0.16419352,  0.16419352]),
 array([  6.56774067e-01,  -2.12663367e-13,   2.12574549e-13]),
 array([ 0.82096758,  0.16419352, -0.16419352]),
 array([ 0.9851611 ,  0.32838703, -0.32838703]),
 array([ 0.49258055, -0.49258055,  0.49258055]),
 array([ 0.65677407, -0.32838703,  0.32838703]),
 array([ 0.82096758, -0.16419352,  0.16419352]),
 array([  9.85161101e-01,   9.16134699e-14,  -9.17466966e-14]),
 array([ 1.14935462,  0.16419352, -0.16419352]),

In [21]:
len(find_orbitals(grid_pts, rlat_vecs))

10

In [22]:
rlat_vecs

array([[-0.82096758,  0.82096758,  0.82096758],
       [ 0.82096758, -0.82096758,  0.82096758],
       [ 0.82096758,  0.82096758, -0.82096758]])

In [17]:
help(find_orbitals)

Help on function find_orbitals in module BZI.symmetry:

find_orbitals(grid_car, cell_vecs, coord='cart')
    Find the partial orbitals of the points in a grid, including only the
    points that are in the grid.
    
    Args:
        grid_car (list): a list of grid point positions in Cartesian 
            coordinates.
        cell_vecs (numpy.ndarray): the vectors that define the integration cell.
        coord (str): a string that indicatese coordinate system of the points.
            It can be in Cartesian ("cart") or lattice ("cell").
    
    Returns:
        mp_orbitals (dict): the orbitals of the grid points in a dictionary. 
            The keys of the dictionary are integer labels and the values are the
            grid points in the orbital.

